# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # # run tests!
      # - run: gradle test
  
  test1:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
        - checkout
        - run: gradle test --tests ParkingLotTest.shouldBeAbleToParkWhenAllParkingSlotsAreFree

  test2:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
        - checkout
        - run: gradle test --tests ParkingLotTest.shouldNotBeAbleToParkWhenNoParkingSlotsAreFree
  
  test3:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
        - checkout
        - run: gradle test --tests ParkingLotTest.shouldNotBeAbleToParkWhenTheSameCarIsParkAgain

  test4:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
        - checkout
        - run: gradle test --tests ParkingLotTest.shouldBeAbleToUnParkCarWhenCarIsParked

  test5:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
        - checkout
        - run: gradle test --tests ParkingLotTest.shouldNotBeAbleUnParkWhenCarNotAlreadyParked

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Successfully deployed
  

workflows:
  ParkingLot:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test3:
          requires:
            - build
      - test4:
          requires:
              - build
      - test5:
          requires:
              - build
      - deploy:
          requires:
              - test1
              - test2
              - test3
              - test4
              - test5
